SELECT * FROM MEMBER;

DROP TABLE MEMBER;

DROP SEQUENCE SEQ_MEMBER_NO;

CREATE TABLE MEMBER (
MEMBER_NO       NUMBER              NOT NULL,
MEMBER_ID       VARCHAR2(50)        NOT NULL,
MEMBER_PW       VARCHAR2(255),
MEMBER_NAME     VARCHAR2(50)        NOT NULL,
NICKNAME        VARCHAR2(50),
EMAIL           VARCHAR2(100)       NOT NULL,
PHONE           VARCHAR2(20),
PROFILE_IMAGE   VARCHAR2(300),
ROLE            VARCHAR2(20)        DEFAULT 'USER' NOT NULL,
STATUS          VARCHAR2(20)        DEFAULT 'ACTIVE' NOT NULL,
ADULT_VERIFIED  CHAR(1)             DEFAULT 'N' NOT NULL,
CREATED_AT      DATE                DEFAULT SYSDATE NOT NULL,
UPDATED_AT      DATE,

CONSTRAINT PK_MEMBER PRIMARY KEY (MEMBER_NO),
CONSTRAINT UQ_MEMBER_ID UNIQUE (MEMBER_ID),
CONSTRAINT UQ_MEMBER_EMAIL UNIQUE (EMAIL),
CONSTRAINT CK_MEMBER_ROLE CHECK (ROLE IN ('USER', 'ADMIN')),
CONSTRAINT CK_MEMBER_STATUS CHECK (STATUS IN ('ACTIVE', 'BLOCKED', 'WITHDRAWN')),
CONSTRAINT CK_MEMBER_ADULT CHECK (ADULT_VERIFIED IN ('Y', 'N'))

);

-- 회원 시퀀스
CREATE SEQUENCE SEQ_MEMBER_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

CREATE TABLE T_IDENTITY_VERIFY (
VERIFY_ID       NUMBER          NOT NULL,
MEMBER_NO       NUMBER          NOT NULL,
REQUEST_ID      VARCHAR2(100)   NOT NULL,
NAME            VARCHAR2(50),
BIRTH_DATE      VARCHAR2(8),
PHONE           VARCHAR2(20),
GENDER          VARCHAR2(10),
CI              VARCHAR2(100),
DI              VARCHAR2(100),
VERIFY_STATUS   VARCHAR2(20)    DEFAULT 'PROGRESS' NOT NULL,
ADULT_YN        CHAR(1)         DEFAULT 'N' NOT NULL,
VERIFIED_AT     DATE            DEFAULT SYSDATE NOT NULL,

CONSTRAINT PK_IDENTITY_VERIFY PRIMARY KEY (VERIFY_ID),

CONSTRAINT FK_VERIFY_MEMBER
    FOREIGN KEY (MEMBER_NO)
    REFERENCES MEMBER (MEMBER_NO),

CONSTRAINT UQ_VERIFY_REQUEST_ID UNIQUE (REQUEST_ID),

CONSTRAINT CK_VERIFY_STATUS
    CHECK (VERIFY_STATUS IN ('PROGRESS', 'SUCCESS', 'FAIL')),

CONSTRAINT CK_VERIFY_ADULT
    CHECK (ADULT_YN IN ('Y', 'N'))
    
);

-- 3. OTT플랫폼
CREATE TABLE OTT_PLATFORM (
PLATFORM_NO     NUMBER              NOT NULL,
PLATFORM_CODE   VARCHAR2(50)        NOT NULL,
PLATFORM_NAME   VARCHAR2(50)        NOT NULL,
LOGO_IMAGE      VARCHAR2(300),
SITE_URL        VARCHAR2(500),
IS_ACTIVE       CHAR(1)             DEFAULT 'Y' NOT NULL,
CREATED_AT      DATE                DEFAULT SYSDATE NOT NULL,
UPDATED_AT      DATE,

CONSTRAINT PK_OTT_PLATFORM PRIMARY KEY (PLATFORM_NO),
CONSTRAINT UQ_OTT_PLATFORM_CODE UNIQUE (PLATFORM_CODE),
CONSTRAINT UQ_OTT_PLATFORM_NAME UNIQUE (PLATFORM_NAME),
CONSTRAINT CK_OTT_PLATFORM_ACTIVE CHECK (IS_ACTIVE IN ('Y', 'N'))
);

-- OTT 시퀀스
CREATE SEQUENCE SEQ_OTT_PLATFORM_NO
START WITH 1
INCREMENT BY 1
NOCACHE;

SELECT * FROM OTT_PLATFORM;

--4. 회원별 OTT 테이블
CREATE TABLE MEMBER_PLATFORM (
MEMBER_PLATFORM_NO  NUMBER      NOT NULL,
MEMBER_NO           NUMBER      NOT NULL,
PLATFORM_NO         NUMBER      NOT NULL,
CREATED_AT          DATE        DEFAULT SYSDATE NOT NULL,

CONSTRAINT PK_MEMBER_PLATFORM PRIMARY KEY (MEMBER_PLATFORM_NO),
CONSTRAINT FK_MEMBER_PLATFORM_MEMBER
    FOREIGN KEY (MEMBER_NO)
    REFERENCES MEMBER(MEMBER_NO),
CONSTRAINT FK_MEMBER_PLATFORM_PLATFORM
    FOREIGN KEY (PLATFORM_NO)
    REFERENCES OTT_PLATFORM(PLATFORM_NO),
CONSTRAINT UQ_MEMBER_PLATFORM
    UNIQUE (MEMBER_NO, PLATFORM_NO)
);

--회원별 OTT 시퀀스
CREATE SEQUENCE SEQ_MEMBER_PLATFORM_NO
START WITH 1
INCREMENT BY 1
NOCACHE;


INSERT INTO OTT_PLATFORM (PLATFORM_NO, PLATFORM_CODE, PLATFORM_NAME, CREATED_AT) 
VALUES (SEQ_OTT_PLATFORM_NO.NEXTVAL, 'NETFLIX','Netflix',SYSDATE);

INSERT INTO OTT_PLATFORM (PLATFORM_NO, PLATFORM_CODE, PLATFORM_NAME, CREATED_AT)
VALUES (SEQ_OTT_PLATFORM_NO.NEXTVAL, 'DISNEY', 'Disney+', SYSDATE);

INSERT INTO OTT_PLATFORM (PLATFORM_NO, PLATFORM_CODE, PLATFORM_NAME, CREATED_AT)
VALUES (SEQ_OTT_PLATFORM_NO.NEXTVAL, 'TVING', 'TVING', SYSDATE);

INSERT INTO OTT_PLATFORM (PLATFORM_NO, PLATFORM_CODE, PLATFORM_NAME, CREATED_AT)
VALUES (SEQ_OTT_PLATFORM_NO.NEXTVAL, 'WAVVE', 'WAVVE', SYSDATE);

INSERT INTO OTT_PLATFORM (PLATFORM_NO, PLATFORM_CODE, PLATFORM_NAME, CREATED_AT)
VALUES (SEQ_OTT_PLATFORM_NO.NEXTVAL, 'WATCHA', 'WATCHA', SYSDATE);

INSERT INTO OTT_PLATFORM (PLATFORM_NO, PLATFORM_CODE, PLATFORM_NAME, CREATED_AT)
VALUES (SEQ_OTT_PLATFORM_NO.NEXTVAL, 'COUPANG', 'COUPANG PLAY', SYSDATE);

COMMIT;